### ISSUE TITLE
Buffer size needs adjusted

### ISSUE THREAD

**Issue by Error1OH1** [Error1OH1/FastFileDownloader#2]
```csharp
Unhandled exception. System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at FFastDownloader.Program.HttpClientDownloadChunking(String url) in C:\Users\Derpy\source\repos\FastFileDownloader\Program.cs:line 27
   at FFastDownloader.Program.Main(String[] args) in C:\Users\Derpy\source\repos\FastFileDownloader\Program.cs:line 17
   at FFastDownloader.Program.<Main>(String[] args)

C:\Users\Derpy\source\repos\FastFileDownloader\bin\Debug\net6.0\FastFileDownloader.exe (process 21020) exited with code -532462766.
Press any key to close this window . . .
```

**Comment by Error1OH1** [comment]
I've tried several different methods to fix this;  copytoasync, setting it via httpclient, setting it in the filestream its self, and a couple of others.

**Comment by Error1OH1** [comment]
Issue has been resolved
